project:
  type: book
  output-dir: docs

book:
  title: "Learning Dairy"
  author: "Geetanjli Rani"
  date: "21/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - About.qmd
    - WeekOne.qmd
    - WeekTwo.qmd
    - WeekThree.qmd
    - WeekFour.qmd
    - WeekFive.qmd 
    - WeekSix.qmd
    - WeekSeven.qmd
    - WeekEight.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

